field: d5e4fa84-5166-47ec-9821-290f8c656179 # Facilities Tabs
fieldLayouts:
  1f641bca-9da9-4ec5-84f9-3b957808fbf3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ff21f52-acf8-473e-bd7e-dc0800668f7e # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15079b13-5641-4844-b37d-bc83393218d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb6b2cf0-cb1b-4e49-aeb4-422309571908 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baf10808-d497-4fad-bdc3-3881e71f2f6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c21181c9-a3a2-4127-8c77-732d2c653ac5 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 957a7672-59dd-44b7-b3f7-f500a388e27e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d37172ce-d5ed-46fd-bc5c-628ab8fbf69f
        userCondition: null
fields:
  8ff21f52-acf8-473e-bd7e-dc0800668f7e: # Heading
    columnSuffix: jighyhog
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: d5ebc5d3-29c4-49d3-970e-80907e54e5d9 # Title H3
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  c21181c9-a3a2-4127-8c77-732d2c653ac5: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  eb6b2cf0-cb1b-4e49-aeb4-422309571908: # Paragraph
    columnSuffix: jaeezfvs
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: null
    name: Paragraph
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: groupFields
name: 'Group Fields'
sortOrder: 1
