field: c6883bfd-18a2-4828-9c01-a69a1e1f7c0b # USPs
fieldLayouts:
  1abb6011-fa67-4740-ac31-32e6ce6ce502:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5e96d5b2-57e0-4eec-99fa-0a099008f7d7 # Selling Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f20a9e23-c476-4431-a26f-e5fcb78ffc32
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fa21b40a-1ec5-4179-9670-1275cdd32f01
        userCondition: null
fields:
  5e96d5b2-57e0-4eec-99fa-0a099008f7d7: # Selling Points
    columnSuffix: wdeaeuam
    contentColumnType: text
    fieldGroup: null
    handle: sellingPoints
    instructions: null
    name: 'Selling Points'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: groupFields
name: 'group Fields'
sortOrder: 1
