field: 1e47f784-5868-477a-a65d-ccd20d3a2eaa # Contact Intros
fieldLayouts:
  1c509a69-1a3d-4cea-b27e-5505298011df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e1ff4cfb-971f-4ad4-887e-8c567c6abcf5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c9b4125-4756-46dc-bdc1-e694b1395b21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82546b52-8a4e-4727-a216-ebae0292e3d9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c068a340-8cf6-409a-8c63-104f563344ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f672ccdb-eed8-47b2-84de-d4340a6f30fa # Contact Detail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1a3990a-8b86-42f5-b48c-100350d3f866
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b262ae7-cc45-4f02-b7fe-e7ef745eee0b
        userCondition: null
fields:
  82546b52-8a4e-4727-a216-ebae0292e3d9: # Paragraph
    columnSuffix: ipsrlbzu
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: null
    name: Paragraph
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e1ff4cfb-971f-4ad4-887e-8c567c6abcf5: # Heading
    columnSuffix: wmcycvpr
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: d5ebc5d3-29c4-49d3-970e-80907e54e5d9 # Title H3
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  f672ccdb-eed8-47b2-84de-d4340a6f30fa: # Contact Detail
    columnSuffix: lzzqssyv
    contentColumnType: string(15)
    fieldGroup: null
    handle: contactDetail
    instructions: null
    name: 'Contact Detail'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - 'Business Address'
            -
              - value
              - businessAddress
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Business Phone'
            -
              - value
              - businessPhone
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: groupFields
name: 'Group Fields'
sortOrder: 1
