field: 68c5d740-f1a6-4bd9-b351-2e5773d12ecb # Features with Icon
fieldLayouts:
  a6731120-97dc-4372-98b2-f203d9017984:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 23f46a1f-4522-4e9d-b95a-988d9d65a2bb # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a8b66d1-aede-4533-9bd1-8690245acd6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7887e1db-5239-4acb-869e-244341183488 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1486fbf1-f3dd-4592-b9a0-5dc0d8e1b6e2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 558281e3-3b00-49e5-a034-16c5ce0b6c6c # Button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fffce5f-5c67-4d2f-8e9b-40102ebede2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15aa301b-549c-4b00-a093-c1d0da96096b # Button Page Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ea457fa-5c29-4868-a061-39fb8b25530a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07ea65b8-2896-4785-b43b-7763da8862c5 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9de36002-ca68-4389-bb97-092d99d7e304
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 632f278d-0dca-410e-996a-7f6df765796e
        userCondition: null
fields:
  07ea65b8-2896-4785-b43b-7763da8862c5: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  15aa301b-549c-4b00-a093-c1d0da96096b: # Button Page Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonPageLink
    instructions: null
    name: 'Button Page Link'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  23f46a1f-4522-4e9d-b95a-988d9d65a2bb: # Heading
    columnSuffix: sblspnre
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 33cfdfc6-431e-464c-917f-25271d27922c # Title H2
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  7887e1db-5239-4acb-869e-244341183488: # Paragraph
    columnSuffix: izzonctu
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: null
    name: Paragraph
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  558281e3-3b00-49e5-a034-16c5ce0b6c6c: # Button text
    columnSuffix: qschkxki
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: groupFields
name: 'Group Fields'
sortOrder: 1
