field: de84809e-27c8-44de-8294-bf2d5eec3aaa # Button
fieldLayouts:
  652bc619-1a8e-4327-8ed2-f9c45e53b4de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6221ad00-05cc-4298-9ace-e6d2b6303c91 # Button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a0539ad-6ba4-4c32-8690-ccbfd7f456a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 491730e4-5d8e-4d79-889a-57fe300b420c # Button Page Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b09c352-16be-416b-9cbf-9636a783f313
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 601a08ae-7ec7-4d90-9a6a-7f3b9c2d8f25
        userCondition: null
fields:
  6221ad00-05cc-4298-9ace-e6d2b6303c91: # Button text
    columnSuffix: iscungwl
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  491730e4-5d8e-4d79-889a-57fe300b420c: # Button Page Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonPageLink
    instructions: null
    name: 'Button Page Link'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: groupFields
name: 'Group Fields'
sortOrder: 1
