field: fa573d0d-05be-480f-b5c8-2eb4c7420d0c # Lists
fieldLayouts:
  bdebf09b-17d4-446e-b741-47d3e7b9ba3a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1c0594f9-f13e-4001-b05e-ef49fc7b0cf6 # List Point
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 090eaff4-bf46-4e0d-b86b-02f83f91d136
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5851c69d-622c-45a0-8681-5bbf23f3cd90
        userCondition: null
fields:
  1c0594f9-f13e-4001-b05e-ef49fc7b0cf6: # List Point
    columnSuffix: igvtukhw
    contentColumnType: text
    fieldGroup: null
    handle: listPoint
    instructions: null
    name: 'List Point'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: groupFields
name: 'Group Fields'
sortOrder: 1
