field: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
fieldLayouts:
  71c4c7b3-ae89-46aa-a4d5-e592137ffe40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9758e6f4-7462-4750-9d36-440d40e64643 # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ac391c8-ded0-40c0-b189-f1a5206cc923
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c1682a4-44ac-44b0-b754-6d11996cf9fb # Paragraph 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c122d2cc-a932-464b-ade5-48c576a428ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23b74deb-c2f9-4c92-b898-5a1b0a1c1dce
        userCondition: null
fields:
  0c1682a4-44ac-44b0-b754-6d11996cf9fb: # Paragraph 
    columnSuffix: kkuzfwrm
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: null
    name: 'Paragraph '
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  9758e6f4-7462-4750-9d36-440d40e64643: # Sub Heading
    columnSuffix: qcmpidbg
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: null
    name: 'Sub Heading'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: d5ebc5d3-29c4-49d3-970e-80907e54e5d9 # Title H3
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: groupFields
name: 'Group Fields'
sortOrder: 1
