field: 07e693cd-5893-4421-915a-a70846a5758c # First Button
fieldLayouts:
  8b434926-aa80-4834-a720-9ca75b1cc17f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c555c40a-443c-4a9e-8b89-9941d417a18a # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df2c0d39-f458-416c-a9b0-c69c5cb81fce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af0fd7fc-a005-402c-b424-cc1002219ab5 # Button Page Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab80530a-bc9c-4442-b765-9593dea85177
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6757f7aa-0422-4bc2-86af-1bb924cee70b
        userCondition: null
fields:
  af0fd7fc-a005-402c-b424-cc1002219ab5: # Button Page Link
    columnSuffix: rorwxnok
    contentColumnType: string
    fieldGroup: null
    handle: buttonPageLink
    instructions: null
    name: 'Button Page Link'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources:
        - singles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  c555c40a-443c-4a9e-8b89-9941d417a18a: # Button Text
    columnSuffix: qicyzgwx
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: groupFields
name: 'Group Fields'
sortOrder: 1
