field: 3ee36c75-6798-4bd2-8772-cbaf669e7981 # Space Selling Points
fieldLayouts:
  d16d742a-2f54-4d60-8a9e-bdd4c4685be1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 41f1a3d3-a8fd-4e2a-ac05-b194f3063080 # Selling Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1fc2aca-b737-4415-8b9d-a2d092bc0d36
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89315cbd-4232-40f6-92e6-085ef52dc66f
        userCondition: null
fields:
  41f1a3d3-a8fd-4e2a-ac05-b194f3063080: # Selling Points
    columnSuffix: wikcccwc
    contentColumnType: text
    fieldGroup: null
    handle: sellingPoints
    instructions: null
    name: 'Selling Points'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: groupFields
name: 'Group Fields'
sortOrder: 1
