field: 93374a9d-1c7d-4731-9d29-906e618f400e # Questionnaire
fieldLayouts:
  12614cfd-1499-43cb-9b13-4071638de854:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 03315e5f-17f7-4ec9-9c09-8bec7d3e223a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db693e60-993e-46ae-846b-112cd6a528d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 67e20c54-bc49-4c79-9385-d7c3e0ddf173 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e85f29a-169c-4f41-b0ee-33775a3863d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07eb9f43-b34c-48a6-be19-0fa0baa63e93
        userCondition: null
fields:
  67e20c54-bc49-4c79-9385-d7c3e0ddf173: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  03315e5f-17f7-4ec9-9c09-8bec7d3e223a: # Heading
    columnSuffix: yanfxsxg
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: groupFields
name: 'Group Fields'
sortOrder: 1
