field: ec014669-2ac5-40c6-b664-a7ea038b50ab # Questionnaire
fieldLayouts:
  95f20686-3979-4ae2-9945-1122fa62688c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 60c6a9c0-a4fd-4f47-bd21-e5a69857356a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f96994fb-289f-4b7d-bcc8-24737b5024a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5aaa255c-eda1-4049-88cf-679ccef5c8ac # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64ffd0f3-6ba8-4737-89e1-9dc418d46de9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7fd3320-6f74-4a14-b057-533855ac1d04
        userCondition: null
fields:
  5aaa255c-eda1-4049-88cf-679ccef5c8ac: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  60c6a9c0-a4fd-4f47-bd21-e5a69857356a: # Heading
    columnSuffix: fxxegavs
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: groupFields
name: 'Group Fields'
sortOrder: 1
