field: b4eebaf7-1d9d-4bca-81c1-b507952d4369 # Grid Add-ons
fieldLayouts:
  8395d971-19de-4284-b5e3-08b59bfd58f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 75c33b8a-3fbb-4031-9b40-b95976dc12ba # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ac4263f-d36e-47bb-ad89-efe5facdeb0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c06f5252-560d-4a13-98d7-2fe4e378328b # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6710c43-12f8-497b-ab38-7bf38e00f711
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 71332b2c-4cdb-49e1-a336-99898cb808c2
        userCondition: null
fields:
  75c33b8a-3fbb-4031-9b40-b95976dc12ba: # Sub Heading
    columnSuffix: iyhvdzab
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: null
    name: 'Sub Heading'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: d5ebc5d3-29c4-49d3-970e-80907e54e5d9 # Title H3
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  c06f5252-560d-4a13-98d7-2fe4e378328b: # Paragraph
    columnSuffix: gtknwnau
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: null
    name: Paragraph
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: groupFields
name: 'Group Fields'
sortOrder: 1
