field: 83ec1284-d751-46da-989b-5ef46b55b332 # UrbanClub Slider
fieldLayouts:
  ce8a56dc-c698-4340-b6e9-4d4e6d2fc249:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34cab00e-4e02-42d6-a3fe-7d2f49769c4e # Slide Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c28625e-4574-4adb-8b5f-9353a17c677f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7947d890-19f4-48df-9f6d-c207065259fe # Slider Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e361db32-2bef-4560-998b-a09ab6bf1631
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c8f2d681-0ee8-4b7a-9344-17acc58a1ffb # List Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 105c6e23-240d-4a99-8b18-a79e955a6ead
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ef1669bd-ae8a-405c-9a65-a8850cf4e279
        userCondition: null
fields:
  34cab00e-4e02-42d6-a3fe-7d2f49769c4e: # Slide Title
    columnSuffix: mdjmpabj
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: null
    name: 'Slide Title'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: d5ebc5d3-29c4-49d3-970e-80907e54e5d9 # Title H3
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  7947d890-19f4-48df-9f6d-c207065259fe: # Slider Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sliderImage
    instructions: null
    name: 'Slider Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:250485d5-f50f-4a7f-a221-1fc9dc7dbb3a' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c8f2d681-0ee8-4b7a-9344-17acc58a1ffb: # List Items
    columnSuffix: xuxcwzot
    contentColumnType: text
    fieldGroup: null
    handle: listItems
    instructions: null
    name: 'List Items'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: informationPoints
name: 'Information Points'
sortOrder: 1
