fieldLayouts:
  778e28bf-1631-42b4-bb35-358ad1f6a3f3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: da22a2b2-81ba-4848-92cd-9d308f91b14d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0521502d-f0fe-4359-a609-b18881058c28
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 792d5f71-9728-4130-a2e8-2257381efbe2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25c9115a-6a61-43e1-97dd-f484eaad2e15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 672e1f78-af98-4cee-a1cd-af9dc5171f84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ea4a118-2720-4326-813b-9aac2ac0950e
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: 4ab76be6-1971-4b86-b8d7-410dc05a48d8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56985cf3-1250-417e-ba85-9ff5472ba6bf # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a561ff05-9897-4cad-9b32-746e8844e914
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58371a45-5631-4796-846b-4a9626da5b18
            userCondition: null
            warning: null
            width: 100
        name: Form
        uid: bf6b2dc6-7c7d-4446-ba17-3c5f660da153
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f03b26a-2498-437b-8c65-335fdcda911a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e98e8dc-a232-457c-8fbb-7edaa3b88a63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36a27b06-ed06-4920-bf44-ad331ee9af9f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26537138-d658-4211-9594-b1c3e2942574
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5ef0c0ef-acef-4853-9c10-e2c6aebe3235 # Button External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09f855cc-8141-4e2d-9d5f-db3264f90efb
            userCondition: null
            warning: null
            width: 100
        name: 'Image Section'
        uid: 226e18a7-baeb-47af-83a8-1c51db1307b7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0249f9a4-8d76-43b5-bf70-de0e1aebee56 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e113d1d9-121e-4815-bd03-032e02ecb749
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Intro'
        uid: bd555384-7fb9-4375-a16b-bf98b0dba6d4
        userCondition: null
handle: contactUs
hasTitleField: false
name: 'Contact Us'
section: 497bf365-748a-48ed-bf4e-0531bd5a8739 # Contact Us
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
