fieldLayouts:
  96f123d5-3454-4089-b005-b89c7e8fc6b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6b416f98-68d4-4836-85f0-d2241466301a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65f266d6-3092-4856-a90d-fdaec2101bc9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a04d00d-71af-4e76-bcd3-91eea084f1c5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe3ce9c-2443-4d72-a8ea-e0d27583ffb7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec5d0113-e7dc-403c-8d32-23ce4cb38f63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5440fd18-f20f-444c-bb08-3e2bb6fd9993 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7cb0114-10be-4f9c-9d0c-48d24e10a9fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5ab6059-ba0e-47d2-99c9-666a41d46bba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 265311ab-cdf9-498c-a3fe-abb5251b703d
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: 9345c0aa-8475-46e0-a911-6bbcd9910331
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 704e30ba-4a95-44f4-92a3-c43acdc64b9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 64c6c4b0-3771-452d-b41d-3d5e76d3c29f # Grid sm
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 932a66cb-d265-4ac2-b501-2d68564f1316
            userCondition: null
            warning: null
            width: 100
        name: 'Small Grid Section'
        uid: 4026f8f0-b198-4f77-910a-a709e4a86fe6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a277371-a262-46c0-a35b-8496f0f7f95e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f085bda5-adcb-4f77-b339-3e1fae4a34a2 # Grid Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aed761da-696b-4844-ad6f-8b5254594398
            userCondition: null
            warning: null
            width: 100
        name: 'Icon Grid Section'
        uid: 29e229d5-a9a7-4848-a247-8a92d13731c1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51a943e3-74c0-4067-8ea2-0d3b1f826827
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 701d3032-1766-4e06-979c-fd973c6b51e8 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 719613ce-8530-465c-b5a6-736e0a2ef03b
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'To add or edit Community Events go to Entries > Channels > Events'
            type: craft\fieldlayoutelements\Tip
            uid: 76a643b4-760d-462c-acb9-1544e72aeee8
            userCondition: null
        name: 'Community Events'
        uid: baee02c4-9245-49ad-9e61-484f767264f0
        userCondition: null
handle: cultureEvents
hasTitleField: false
name: 'Culture & Events'
section: da96f250-8ec1-45a1-81bf-58b56467d573 # Culture & Events
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
