fieldLayouts:
  e016bd52-c0d5-420c-8325-26afc5817a98:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cce0b71c-d1cf-4c1f-b82f-7cbfbb5838b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5908f86-11d8-49a9-b0fc-1dc187009d66 # Space Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa29f89d-bbc8-4029-898b-14608196eb4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4086dd2d-a840-4155-b992-eecd835319cc # Dollar Sign
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9a8d649-1d77-4efd-83e0-0ba89fff5f4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb88e673-2a3d-4557-aeea-9fd63d7d74fc # Space Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af04ed4e-93a0-4f3e-9c7d-51ace0e0d243
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4c8bceef-38e6-4299-9198-ae6c832a644c # Price Quantity
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44e8b924-3d6c-4692-b907-c73c50d279fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1089edbe-d415-44fb-84ec-54cc1bd33633 # Space Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10b4834c-5134-41dc-9ff1-143162d83c90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82f704c3-36ac-4f0d-b835-560746906020 # Button Text
            instructions: 'Slide linked to corresponding page automatically '
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c617b7a9-7026-4c4d-bf92-a9be9b9efbf2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ee36c75-6798-4bd2-8772-cbaf669e7981 # Space Selling Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c60ec50-56d9-474d-824e-9eb6e1a26aa9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a03c41e-c6f8-4eed-941a-a12c9f8c463a
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 7d73696a-27d3-438f-84cd-2d5fd1e9c0d5 # Urban Solutions Slider
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{spaceType[0]}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
