fieldLayouts:
  3654cd57-0e2f-4685-9431-639e06447a53:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19d4347e-e6f7-4eaf-b28b-67c86ee9753c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 701d3032-1766-4e06-979c-fd973c6b51e8 # Paragraph
            instructions: null
            label: 'Tab Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1af81ead-d919-4229-9bd6-897d2dca6a61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7211e06d-99d9-46f7-a0b1-e7c20c5dc332
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31a6a6cd-809b-4018-b66d-eb3c366fc392 # TableEditor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de02f6b6-5cfc-417b-a622-ffbaba78023f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0e5148ab-9ad9-4874-8c7d-9d5d9adb57f9
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 261c18b2-1b1d-4729-9d6b-7b05a5c91307 # Solutions Page - Tables
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
