fieldLayouts:
  003c28e0-5bb7-4c62-b511-a54038707256:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: af3b627a-988e-4ea1-9993-4df0385d56ba # Staff Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edbc7930-d303-4ba3-89e0-aafa7e7c75a4
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Staff Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7837a6cc-a9a3-4790-a463-f569b633d674
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b19f44d-dfcc-4769-b2ae-47e67f653eb2 # Staff Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22941d06-152b-4d25-933a-c8b1ab394535
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f70e299-ee8c-44cb-bfba-644bd49af8b7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f0e30fc6-403e-4a73-8c7e-0e24edde01f6 # Staff
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
