fieldLayouts:
  d26a3685-d1d2-4729-9665-9f245c089f24:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f696e434-6965-465f-b871-060428534c74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0136f64a-860d-422d-9766-d0ffbd8bbbc4
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: a52eca91-62e3-449d-8981-6f98a24591d8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d49eb71c-b369-4c4c-a786-0fe40157f04e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c492cfd-f335-4eef-805d-04e92f855c99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8028e1b1-0dd7-4a82-a345-b889ff2c28bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 917e19fa-bdd0-44f7-b44e-15582bf1eebf # Building Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d37e885-898f-4d95-811a-bd729da1dd56
            userCondition: null
            warning: null
            width: 100
        name: 'Panel One'
        uid: c89dd06a-0bba-48e6-ab0e-ef71086643f0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe3e53ca-ab17-46d0-8015-f49e2ed58d28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 809b1524-bf46-4a43-b861-33929c69b76c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c0ed38c-11e0-4bbe-baee-3a545a75a51e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0b87284-c2cd-45ca-927f-03f9558c3cb0 # Building Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c7bfbdc-1ef2-4e80-ba50-715ab31cc758
            userCondition: null
            warning: null
            width: 100
        name: 'Panel two'
        uid: 17e78442-4cec-4d02-bae6-51c40403f898
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8390b227-7014-4494-8650-60b152169492
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb2e6aac-abcc-4744-9ee7-250b2502df0d # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd6c2159-a359-4efd-b3db-8724fdf42869
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8be806db-3051-4e01-a8a8-823d359dbfd2 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56673580-b484-44d8-b07a-5a5eeac4fba8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58a23fd2-b9ed-4834-9d91-a5b824101f1f # Building Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9a8ad9b-d6b6-4b61-853e-ae1d98740d66
            userCondition: null
            warning: null
            width: 100
        name: 'Panel three'
        uid: 3ccf8477-b9c9-4772-bef9-c82906358fd5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d7f516a-7f14-4b60-bd49-36ae346e5264
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 745e6158-28f3-446a-883f-91c614885da5 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8c9ab30-0ac4-4e1f-bdd0-82be1f831ac2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 701d3032-1766-4e06-979c-fd973c6b51e8 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78f8c5d7-0cbe-48ad-854a-c4326cbb15d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4295a173-ae5a-47ce-9796-04bb2046bc2f # Building Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecb0453a-f6dd-46fe-859f-550befa16fad
            userCondition: null
            warning: null
            width: 100
        name: 'Panel four'
        uid: 94a264e3-b5e1-45c1-af7c-5969cadb2862
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94ae2f64-db35-47c0-907e-b853e95b3ce5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d8d365b-e6d0-4a33-9b09-7f5ff43cf0d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d12001e-f75d-404c-9359-4dc9751c2833
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbdf5c9c-3d61-4c53-94fa-4ee400e528ff # Building Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5be1551c-0748-40e0-bcf8-d253bb0e53bb
            userCondition: null
            warning: null
            width: 100
        name: 'Panel five'
        uid: de7ffc0e-69a1-4f4c-ab6a-df3d4806984f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34804f61-aab1-4122-8907-cc55a4677fa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f85f8d4-c326-4e72-a8ae-bfa5c037b407
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc5656c9-ee2c-497e-bab5-2bb3f236be53 # Footer Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bdd6eb4-745f-4a83-b153-1c4f5fa6359e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89723374-3eac-4abc-b3ad-1bbd27091648 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fba3114-4207-4fe1-af77-8afca1d3b5c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea48c9dc-6e22-48a2-8f56-385fa9fa259e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55794c45-7d8a-4c8a-94f1-53605e54b59a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b780b22-e03b-4537-bd01-74db803e4b3a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8793cd89-56b5-499f-a5c9-54e8fea293e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d08c9cda-b4c0-42b0-a7e5-c654a94f6fa2 # Pargraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deb8c981-1751-4335-b4d2-ada2f56fceb5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d32e2df-7698-415c-9640-62e6787a0270 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3d69073-cfa2-4fe9-b5b5-b86a3f4406a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d48d0ef1-ee78-4bd5-8dc8-21ad80e2eb5e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bf73ee2-deb9-4a8e-8520-f99d339c57b2
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: 7bb117fa-5078-4fc4-88c4-d7222e35a85c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4229ea84-84b7-4d2e-a96d-e4be1b495643
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7bd485b-d43a-4b9e-90ad-47b23826702f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6b2c99b5-ceb2-41a9-9f11-a41e26422e23
        userCondition: null
handle: exploreOurSpaces
hasTitleField: false
name: 'Explore Our Spaces'
section: ad2fa7ed-3fb2-4493-97ef-5a303e5ca6fa # Explore Our Spaces
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
