fieldLayouts:
  c017a958-4b42-4926-bc2d-4cce2bc6547f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b71db059-7e88-4373-80b4-1bc9af4b5c14
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fb97414-79f5-470b-97b1-a23a1ae49a9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31a6a6cd-809b-4018-b66d-eb3c366fc392 # TableEditor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b6e1128-cfba-4465-a5f8-d8d9fd3e328a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a27e01d-23a1-46f7-b29b-a1daf1187f14
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acc955d3-824f-421a-8c9b-e3c4a3c936fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7026ee6-da06-4f35-936c-ab7927d0d353
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e89d462-7386-4524-91a9-3abfd34e458c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ef38e85-d3af-4225-94d1-2ef3a1456c07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de84809e-27c8-44de-8294-bf2d5eec3aaa # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ebd46ca-c085-422f-8b65-a2d7dbbe6d94
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86a285a5-8281-4ecb-860b-3a0e24c015cd
            userCondition: null
            warning: null
            width: 100
        name: Section
        uid: 74bb6db2-2ec9-4e2d-bdbf-5c1c0cb6ee85
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56985cf3-1250-417e-ba85-9ff5472ba6bf # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b6399f-d420-4bcf-a7d7-31ade42bffeb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6883bfd-18a2-4828-9c01-a69a1e1f7c0b # USPs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c336fd8f-7c7f-4196-a606-277a1eceef0c
            userCondition: null
            warning: null
            width: 100
        name: Section
        uid: e62444a8-40ae-4258-9670-75336017433c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 031d1333-791a-486a-b988-5a017edd1c03
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1a0d627-969d-477f-9567-99f64da9e245
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d9a7b30-3d81-4f71-bcf3-6c20bbf990d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f905e985-cd04-4a75-bad6-a55319d80111
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa573d0d-05be-480f-b5c8-2eb4c7420d0c # Lists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4034dd0a-e60b-42a2-a070-2192e8909682
            userCondition: null
            warning: null
            width: 100
        name: Section
        uid: a8984e06-fee8-496b-8a29-d16d417b987b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28a9556a-0be6-46f8-bf09-938c061c2ca0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 074633c4-cdda-4010-8724-afbfcb9d9c90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4576554-babe-4b25-a6b0-d9af9b091395
            userCondition: null
            warning: null
            width: 100
        name: Section
        uid: 5b12e258-8823-499e-a061-e5d42f08301d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c743db56-3337-471e-a0e5-f2be9be59880
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c772a7e-10cc-4687-813b-9b8f08dafd6f
            userCondition: null
            warning: null
            width: 100
        name: Section
        uid: e96c2cbc-b5d1-4ff6-aef5-ff2b87922491
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19df8bd9-d1b5-4bad-81a9-257faa630760
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ca3f21f-2832-4039-be1c-de50d73e0723 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4ffb671-773d-4bdc-8f33-386342750479
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4eebaf7-1d9d-4bca-81c1-b507952d4369 # Grid Add-ons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4734e0c0-b0d9-4d50-b520-8e96d903aac1
            userCondition: null
            warning: null
            width: 100
        name: Section
        uid: 1256774e-8c3a-46a0-8e77-767ebbd971c6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94ae2f64-db35-47c0-907e-b853e95b3ce5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81db900d-e0df-4b99-8040-db23fdedf35d
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'To edit slider content go to Channels - Urban Environment Slider'
            type: craft\fieldlayoutelements\Tip
            uid: 20d2bdcf-8a80-484b-aa60-a8aa9a92e0a6
            userCondition: null
        name: Section
        uid: de256b03-6493-4e2a-ba5e-0c5b27239399
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: c406e842-e9ae-4fa0-9851-a74a6f9cedf2 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
