fieldLayouts:
  101d2e69-475d-4aae-98a3-6c28c14580f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 07cbf34c-4b96-45eb-9b6c-423a14b4351b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65541ba4-cc18-4916-81bf-6ebe3b79823b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca5c3a2f-ec63-4d2d-bb11-f916b9e3faa8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7c497ea-5a96-4e8b-b971-20a13ec7aac9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 244a2ceb-e073-4324-9b79-a4e141c34ad7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1a1b373-2201-4b53-9c23-6c3c64e74e17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6e3a262-ccb8-4bcd-aaab-af295a238433
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de84809e-27c8-44de-8294-bf2d5eec3aaa # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d578f888-d11b-4171-93dd-9b1e32f61406
            userCondition: null
            warning: null
            width: 100
        name: 'First section'
        uid: 62bebcb9-380a-4c97-afed-92d0f7c0ef6f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da273b2c-01bd-4b71-ae57-ae1ca2a86957
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56985cf3-1250-417e-ba85-9ff5472ba6bf # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb1ec900-3d13-45d4-895d-49902ec7f08c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da4f075d-e324-478d-830f-030d1d94d314
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44d6c7ea-2e11-420a-bf28-b1f1d27fcd70
            userCondition: null
            warning: null
            width: 100
        name: 'Dark Image Section'
        uid: 400c0412-8029-470d-a0ca-5fb1fc4e909a
        userCondition: null
handle: neighbourhood
hasTitleField: false
name: Neighbourhood
section: 3d94fda3-efd1-473e-883d-19ce15bc6846 # Neighbourhood
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
