fieldLayouts:
  d5f11689-cd43-4a2e-b015-33209b786005:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c75ec38b-7681-4364-b9ee-77be9da514c9
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1836eaff-eab0-44d4-953d-a7d3583965ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7276194a-105e-448c-ae16-4eb5f0eae227
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8465255b-8aac-43bb-b070-55d156d969da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bfb7b42f-4864-40c5-861c-2e94d9335067 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea3f650b-2450-4bb8-8f3f-fce1eac0906f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c1dca96-5882-4381-8f3c-4521e9e90be9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5476015c-cc38-4238-9589-80ae5a8b172a
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: 3c2548b2-af8e-484e-85dc-240a3b53347d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 01e3ac64-8ca0-44cf-839a-89c52910615c # Wellbeing Slides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf1083e1-14f2-4d0d-b022-d862858ea8b2
            userCondition: null
            warning: null
            width: 100
        name: 'Feature Slides'
        uid: 87055cbd-649d-4b7b-b9cc-30de6feb7dd0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbee2f6e-ac60-42b9-9de0-917abf2396d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ab0e1d4-69f6-432f-82f0-e0aa0baeeea9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41ec338d-aa8b-4096-939a-fcb97e57e039
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f2f0dac-af45-4054-97b0-d4d80440c0d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d179adcc-4b06-4a3b-85b4-aaff28d7ca0b # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3fdb5fe-42b9-4e09-92ea-df8b6f28f48d
            userCondition: null
            warning: null
            width: 100
        name: 'Main Image Section'
        uid: 62134eab-d489-485b-9450-82db9f709af9
        userCondition: null
handle: sustainabilityWellbeing
hasTitleField: false
name: 'Sustainability & Wellbeing'
section: ebeeab65-582c-4636-83f4-03789c4ce17c # Sustainability & Wellbeing
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
