fieldLayouts:
  92294eb9-991f-406f-b934-804802601f6a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 53f8fce5-1c26-44f1-9ce8-f5d5debd2482
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d435ab56-3374-47ba-8332-0ea421e977ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d8b5a3f-3b1e-41d4-aac8-3f4b5c2a68a6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1a145fe-55bf-4dde-b750-4d6aa9cb0e37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db94cbb8-0eb4-4143-9674-99b71cdb2777
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bda35a5-ff91-40d2-9f05-cbf525a141da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25d01eaf-17c2-4b82-98af-27ee17e2bc89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de84809e-27c8-44de-8294-bf2d5eec3aaa # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25cab600-4834-4fff-9c04-0ef76acaf961
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f916a436-1840-4b1b-b60f-20dbb22c947c
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: cb12b1e4-ebe5-419f-a8c9-17f3398fd9a7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56985cf3-1250-417e-ba85-9ff5472ba6bf # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ada1175-98ee-4fb9-8ffb-3892b7b85add
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6883bfd-18a2-4828-9c01-a69a1e1f7c0b # USPs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a21338e-8582-4ad4-b63a-7c2bb6ba2ba6
            userCondition: null
            warning: null
            width: 100
        name: 'USP Banner'
        uid: 741ba850-7ee8-4a51-a7ca-f8e1166a56d1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf91992b-91cc-4ebb-93b4-a8d2d57732c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02c9e5a0-78e4-44ea-a6fc-51581977d301
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d856250b-05a4-48b5-997f-9e59969f99ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f24d4c5c-35d3-4d22-b2b0-b7098f754a22
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa573d0d-05be-480f-b5c8-2eb4c7420d0c # Lists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be4ea75a-c59e-4a29-8c37-b6f949b166b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4678540-d902-4f16-80c3-064fd7650f41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68aed564-f86a-4bf2-a906-d525fe53a8c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c314fab-2dc1-43f6-85fb-e13954cb8916
            userCondition: null
            warning: null
            width: 100
        name: 'Large Image Section'
        uid: 0c530bb4-4a4b-46d2-a858-00913090d4ed
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bae9b8b0-f913-4f59-846e-6be7aed27439
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5021676e-6732-4fc4-97c2-44089e240877
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b61b3b6-b31b-42cd-afca-73b839c6f4a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ca3f21f-2832-4039-be1c-de50d73e0723 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eae286b-48ef-4b86-bddf-1dac800faaae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4eebaf7-1d9d-4bca-81c1-b507952d4369 # Grid Add-ons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c40f94b2-be1c-4bea-8a17-04f66bdd3b8c
            userCondition: null
            warning: null
            width: 100
        name: 'Membership Section'
        uid: 07a00226-6eb9-43b3-a305-01cd8436046f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94ae2f64-db35-47c0-907e-b853e95b3ce5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dd7d537-698a-4e5f-b557-f9c1a45298a6
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'To edit slider content go to Channels - Urban Solutions Slider'
            type: craft\fieldlayoutelements\Tip
            uid: 4b263831-1c61-4ac9-971a-0f151ae318c1
            userCondition: null
        name: Slider
        uid: 45a0606b-895b-4b78-9375-f2c59c40bca3
        userCondition: null
handle: urbanOffice
hasTitleField: false
name: UrbanOffice
section: 55a2395c-c1e1-44dc-ab10-3eb438f40eaf # UrbanOffice
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
