fieldLayouts:
  ac004903-0418-4ddc-b2fa-e37fdac77d50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 24eeae15-45ae-47c9-acb3-dda0cb07ea6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 153d70e0-0143-4128-86c5-4fa2c19072d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 84f3ff06-7c25-4ddf-8917-9f3f40c24b1f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d169ccfa-3754-4d86-969c-aed307634b24
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 248d57e5-aea2-4fd2-929c-b453f2887b0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7208a4af-f595-4cdb-b379-f7b2b93af033
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7b6d315-021f-4f6b-932b-be8ff89772ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de84809e-27c8-44de-8294-bf2d5eec3aaa # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a2ad561-a450-4705-9e0a-fc65c3e33ee9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 503e4805-6ff4-4b6f-9ad4-4e5c2643d0c2
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: a717c4b3-9bef-4841-aabc-66bb1b8d31e7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56985cf3-1250-417e-ba85-9ff5472ba6bf # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df346e8e-6a88-42cd-a346-e939ce7eaa44
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6883bfd-18a2-4828-9c01-a69a1e1f7c0b # USPs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c66785d-a1ed-41e6-ba6e-17bb826b0a9f
            userCondition: null
            warning: null
            width: 100
        name: 'USP Banner'
        uid: 7ca7dc27-0510-42dc-b220-791a0909eb63
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39d43852-bcf0-419d-86be-cea5c3b5b140
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4ba4ede-c1b5-4638-89af-803c8b7e4496
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ad302a8-ddea-42d8-8416-6815fe013451
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c20ae65-727f-41e5-875f-0dc57b67939c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa573d0d-05be-480f-b5c8-2eb4c7420d0c # Lists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2c74f63-3548-4f38-9ec5-215b175c678e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 723186a9-a085-4185-ab42-e61e22539abc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f49890c4-2aea-455b-836a-bb2196751082
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55deaecc-eea4-4958-af7e-5022a627e207
            userCondition: null
            warning: null
            width: 100
        name: 'Large Image Section'
        uid: a2d1d922-85cc-4f7e-a020-7dca8c2406ae
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae492c32-61b2-4984-9f43-d6daa1b998a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47ce1f4c-acfd-4987-8ecb-fa43c6918dc1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32998d7c-58d3-4466-a8de-233e8618b734
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ca3f21f-2832-4039-be1c-de50d73e0723 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccb1330d-b22b-4a43-b545-5b4a09939596
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4eebaf7-1d9d-4bca-81c1-b507952d4369 # Grid Add-ons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3310ec92-3cc1-47f9-80cd-880bfe4aa8d3
            userCondition: null
            warning: null
            width: 100
        name: 'Membership Section'
        uid: 9d52eb95-abf0-47be-9c53-87599ef910ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'To edit slider content go to Channels - Urban Solutions Slider'
            type: craft\fieldlayoutelements\Tip
            uid: fe1133e7-41d3-4c4c-86af-176e179d59f0
            userCondition: null
        name: Slider
        uid: dfc91600-29a8-4888-a2e8-c952f66594da
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34804f61-aab1-4122-8907-cc55a4677fa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18db41b5-6d7c-4445-82a9-56a325c01095
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc5656c9-ee2c-497e-bab5-2bb3f236be53 # Footer Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0153a89a-ca08-41cd-8d4e-6e50908a77b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89723374-3eac-4abc-b3ad-1bbd27091648 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 864e64c5-24c7-416b-8f13-46f70961eaa7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea48c9dc-6e22-48a2-8f56-385fa9fa259e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1bd1cbf-1d05-4ec0-9b6d-d99c2576ee63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b780b22-e03b-4537-bd01-74db803e4b3a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7b23135-fef7-43fa-bda5-d72718d30297
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d08c9cda-b4c0-42b0-a7e5-c654a94f6fa2 # Pargraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bafd0e50-81e3-4f13-8c01-c07fccde3a5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d32e2df-7698-415c-9640-62e6787a0270 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a6e7f33-6f56-45ad-900d-107af111ab29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d48d0ef1-ee78-4bd5-8dc8-21ad80e2eb5e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65d1c7ab-02a6-4ab7-8232-ecfb31cce879
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: bcef5faf-65d4-4a55-84b0-5f0cabdff049
        userCondition: null
handle: urbanlease
hasTitleField: false
name: UrbanLease
section: a33a9b78-e67f-4d71-b70f-5c91db0323fe # UrbanLease
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
