fieldLayouts:
  4c5386ed-6eaa-4e40-984b-0fb5b35b05e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 56189a60-7b92-413b-9611-92f300f6fd58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5f0588a-0617-4f59-aea0-0f799d747578
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f86f6005-a1d6-4dad-abef-952da5d656ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8086a2d8-14de-4f5e-851d-dd3abb85611a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2f3f9e7-1df4-4aaa-b619-28693e1ef02d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60946247-8c64-42f7-9b55-e23f5a4700eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6af97cb-1191-4802-b797-2d80795cc531
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de84809e-27c8-44de-8294-bf2d5eec3aaa # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edac02c9-e673-44ab-b17e-69281ae2dd9c
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: 46a91593-e68e-4b91-a574-d0c99db6f24d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0249f9a4-8d76-43b5-bf70-de0e1aebee56 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e64f7ef-a04a-486c-bc5c-e5338baeff11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 83ec1284-d751-46da-989b-5ef46b55b332 # UrbanClub Slider
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd3c6f69-d2b2-4db3-8fa3-754b1f036f90
            userCondition: null
            warning: null
            width: 100
        name: 'Urban Club Slider'
        uid: caa8d3c6-bf2f-4ae6-9315-b0a73f9ba47c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1497dfa-4658-4c1b-84fe-4312e5022c61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adea373a-c6ec-40e6-97cb-3bc6ae7a1dc7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da25b666-e25e-453b-8312-62a62e4e60d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb6f291e-9d49-4d0a-906a-1bd32ecab1ff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa573d0d-05be-480f-b5c8-2eb4c7420d0c # Lists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3091ba19-1074-4cf8-8316-911b0ca4e703
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29f83aff-131b-45f7-9182-c3899b47853d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07a94cf1-84fc-409d-b584-92ca634af5fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a2f1198-68dd-4810-a2c1-274433331dea
            userCondition: null
            warning: null
            width: 100
        name: 'Large Image Section'
        uid: f380596b-c83b-4262-9ade-69312f4ef7b6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d71fbf2-2c08-4b64-b82b-6f3d2b212497
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18b747a3-60ba-4ef9-b884-f3842454f08f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c71ea34-2de3-4d38-a86b-836576a27ac1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ca3f21f-2832-4039-be1c-de50d73e0723 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acb848f7-c18a-4f39-85b0-bbf18374db29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4eebaf7-1d9d-4bca-81c1-b507952d4369 # Grid Add-ons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d08c2c20-abbd-4237-b9ae-a97bebb51b01
            userCondition: null
            warning: null
            width: 100
        name: 'Membership Section'
        uid: c239e877-714e-4058-94a2-eb002297832d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94ae2f64-db35-47c0-907e-b853e95b3ce5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09e9c53d-d35e-4b33-b28e-5cb9f4103aae
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'To edit slider content go to Channels - Urban Solutions Slider'
            type: craft\fieldlayoutelements\Tip
            uid: 4f57b730-2bc6-4b7f-a37a-b3231e341782
            userCondition: null
        name: Slider
        uid: b3847051-f1bd-40fb-a8dc-23c3125235f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34804f61-aab1-4122-8907-cc55a4677fa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 350c67ea-e304-4f9f-becc-3825c8deff03
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc5656c9-ee2c-497e-bab5-2bb3f236be53 # Footer Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ff2110a-8f6f-4c54-a515-a6b7128c4f47
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89723374-3eac-4abc-b3ad-1bbd27091648 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fd4f8d9-a27f-4d80-bff2-26367c451047
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea48c9dc-6e22-48a2-8f56-385fa9fa259e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 213ba5f6-f4c4-4a7b-b9f2-d9a0f6f39691
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b780b22-e03b-4537-bd01-74db803e4b3a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eafcfb01-37ec-4d52-9bd9-4601b95aa973
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d08c9cda-b4c0-42b0-a7e5-c654a94f6fa2 # Pargraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d56b42b5-6736-4431-9c75-3a0b57f7e813
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d32e2df-7698-415c-9640-62e6787a0270 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2620a76-0417-45b6-96b3-a80712efb1e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d48d0ef1-ee78-4bd5-8dc8-21ad80e2eb5e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0dc7bb4-2003-4a9f-abd7-c6f992d0be3e
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: a9f29b02-00b7-48dc-af88-d3690ec792f3
        userCondition: null
handle: urbanClub
hasTitleField: false
name: UrbanClub
section: 0fadc91b-326d-4899-8d25-c5f9bf36b802 # UrbanClub
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
