fieldLayouts:
  9e11494d-7449-4f46-a37d-fb51b5f0c5a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d4c59bb-8701-4c60-b0fe-8359d9e5887e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eba6ce9-ed4f-4b1b-baab-658766a16978
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f822c080-2ee6-4938-aba5-1571faa158be
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6870637-a77f-43ad-91c4-cc34cca91c5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdf6b450-36b0-49c3-9568-5495d2a9baee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb8de2cf-fd9e-478c-a1ed-79bf5b0f46fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b33f2a0f-5d00-4dff-bd98-883b901c8b65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de84809e-27c8-44de-8294-bf2d5eec3aaa # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cad0bd17-de2f-4f51-8302-3b11d7f11ae9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5abbc462-1587-4a32-a3b8-66697066bc1e
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: 58916c67-a0a2-46a5-a2d4-b88e377e5e1f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56985cf3-1250-417e-ba85-9ff5472ba6bf # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec9dd34e-11b8-498a-9c57-796ba751938e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6883bfd-18a2-4828-9c01-a69a1e1f7c0b # USPs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7b4621c-1c01-48b0-a873-04a90b83309e
            userCondition: null
            warning: null
            width: 100
        name: 'USP Banner'
        uid: 34e92b39-0c7a-474a-9fd4-94b33e0a7f13
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbb0088f-8811-4e40-a24c-582d89197464
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f153b14-a61d-4c56-9ae5-06ab531ab0ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d03d38b-6c89-4333-8ef4-4e1922bfa50b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7069261-5f7c-4b8d-9605-ac75b0eabf96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa573d0d-05be-480f-b5c8-2eb4c7420d0c # Lists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6323521c-2fcd-4e16-9130-43dc9557d690
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a08adc9-ba5d-45ca-a33d-adcd60fd0a9f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8c80466-63ab-4c87-a2a8-61305e30a3be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ba3a210-8e57-4492-b80c-d359c8b0e9d6
            userCondition: null
            warning: null
            width: 100
        name: 'Large Image Section'
        uid: 49f0ebaa-008e-417c-abb3-9b566d331f2f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9587b5de-82c8-4f8e-bbcd-1140a5fc71bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d9d8558-63c0-4143-844c-0d3c2dacaac9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be0323ef-2167-4962-bd93-775959db4a93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ca3f21f-2832-4039-be1c-de50d73e0723 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcb85b2c-0657-448b-9385-b381ce4fd4ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4eebaf7-1d9d-4bca-81c1-b507952d4369 # Grid Add-ons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de718c89-a9c4-44c2-81a4-2d43f7182aca
            userCondition: null
            warning: null
            width: 100
        name: 'Membership Section'
        uid: 7485add7-92e1-4df5-920a-164148aba0d1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'To edit slider content go to Channels - Urban Solutions Slider'
            type: craft\fieldlayoutelements\Tip
            uid: 8218f1ab-a80e-4a38-8bab-e059ce5b71bb
            userCondition: null
        name: Slider
        uid: aeeb7216-33ab-431d-bc54-fb9d8869e088
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34804f61-aab1-4122-8907-cc55a4677fa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 680f0aa9-56dc-4b90-a5f0-532617aeeebb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc5656c9-ee2c-497e-bab5-2bb3f236be53 # Footer Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1806118-5b2a-4992-907f-12c78ffc9a0d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89723374-3eac-4abc-b3ad-1bbd27091648 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edaa07cb-314b-41c4-a299-da30e158383e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea48c9dc-6e22-48a2-8f56-385fa9fa259e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 792201a2-7ada-4cfd-a26a-68c4b1d524fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b780b22-e03b-4537-bd01-74db803e4b3a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2abea628-0d83-46db-88fd-4d428bcbb506
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d08c9cda-b4c0-42b0-a7e5-c654a94f6fa2 # Pargraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1117de1-8e4a-41c5-9a2b-281813f12db2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d32e2df-7698-415c-9640-62e6787a0270 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b511a9bf-b1bc-43c0-9f95-ddbc89636663
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d48d0ef1-ee78-4bd5-8dc8-21ad80e2eb5e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73e70d33-1228-496d-acb9-58e96768edc5
            userCondition: null
            warning: null
            width: 100
        name: 'Footer Section'
        uid: fd291004-fd8d-47b4-a23e-aecbb11b4a1b
        userCondition: null
handle: urbanDesk
hasTitleField: false
name: UrbanDesk
section: 910635d5-1696-4b6e-995f-1141ec5da6c0 # UrbanDesk
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
