fieldLayouts:
  7bdf9918-a9ce-4072-a81c-3c57d6750131:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0249be18-f2ae-4232-87ae-1195bbfc4a0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b1a6d2-d5a8-4791-8722-91479f5bf9ae # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 594f0913-3976-43e1-b64f-10768a9eaab1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 51f7d249-daae-4af4-8910-f249c8591d62
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bfb7b42f-4864-40c5-861c-2e94d9335067 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5f7d033-3ee2-45b6-ad86-cda659a987c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c48acb5e-af1d-4c28-a2ff-70fd3988e3a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07584cfe-a4ba-47d5-b553-b4ca5a34d9a2
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: c981202f-32d0-40c1-bd01-8ecbd73571fb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b37ae5b-3fff-48ce-9880-b91a8ab76d67
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dd0892b-a1cc-4b66-a7ed-623e1577c8cf
            userCondition: null
            warning: null
            width: 100
        name: 'Second Section'
        uid: a6e1d9d1-dd52-43c7-ad9e-2de1dfdba8f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 68c5d740-f1a6-4bd9-b351-2e5773d12ecb # Features with Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fa39c8a-b9c7-473a-a445-d57a0a6b7cb0
            userCondition: null
            warning: null
            width: 100
        name: 'Third Section'
        uid: 2a174f9c-36f7-4ec0-bb77-11e29834f5f2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16d346b7-0871-4ca2-b121-f8afd2288172
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 745e6158-28f3-446a-883f-91c614885da5 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9f6d6b2-9349-4288-938d-52a06d55e6fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 701d3032-1766-4e06-979c-fd973c6b51e8 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 957a1f0c-337a-487d-a6fc-f42f764a9305
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ca3f21f-2832-4039-be1c-de50d73e0723 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4308f3ad-6160-4925-8e55-533c200f493e
            userCondition: null
            warning: null
            width: 100
        name: 'Centered Section'
        uid: 7162a0b3-f638-4400-afd1-4b2ebaad29a1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1ccdca9-7d48-49bd-be39-4419d188df15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69720f16-fcbf-465f-bd77-440deedae577
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 680a4f7a-aac2-4bf1-9af5-3bc456fd1239
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e4e76db-030e-4e7b-9406-84cba8b6ac7e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d179adcc-4b06-4a3b-85b4-aaff28d7ca0b # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 585a4238-fdc6-4486-8895-ed9d7c0e3c33
            userCondition: null
            warning: null
            width: 100
        name: 'Main Image Section'
        uid: eeb9475a-cf52-418d-9610-c258837a273e
        userCondition: null
handle: urbanCommunity
hasTitleField: false
name: 'Urban Community'
section: 3cfc94ea-b426-43b8-9e50-d525f47c2148 # Urban Community
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
