fieldLayouts:
  322b18ed-d02b-466e-997d-74ad8f3f7d87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 066d0095-f707-40ed-a009-48f09b936f36
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 746d2079-784a-4985-a472-54a08248cbdd
        userCondition: null
handle: urbanSuite
hasTitleField: false
name: UrbanSuite
section: 319d4674-6b0e-4027-abdc-23a8fe7bcf1f # UrbanSuite
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
