fieldLayouts:
  2b012d16-9d98-4c86-a6d3-e08bc0009e88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 938f8f0e-2e28-4c11-ba9d-8bab1051d4ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a64c6ea-1517-4f29-ba3b-d7ad5e5902d4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1bf7809-a0ec-476f-84d4-9d9bb2f451f4 # Page Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3ce384c-61bc-48dd-b13b-3e1575c29fe8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368e19da-aed2-4692-949d-976508166279 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a6fc271-8a1e-4cee-ba0c-8ce7475a24f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d199f8b1-8c10-441f-8951-d2f10491a634 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6697e08f-4e8b-4d9e-813d-52f0f38125a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c093fd38-7d2d-4d3d-b514-a314fa8fd189 # Page Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9cbe24b-e08d-466b-972d-cdb072c24e29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05bce30c-4a94-454c-9c35-7cfa54523a96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5ef0c0ef-acef-4853-9c10-e2c6aebe3235 # Button External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 774c9b45-cd0c-4c5c-b164-f5a80fa7720d
            userCondition: null
            warning: null
            width: 100
        name: 'First Section'
        uid: dcecf50b-e645-4155-8819-f26645cf3de2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56985cf3-1250-417e-ba85-9ff5472ba6bf # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd8a4c07-adc4-4e43-943f-19e39145fc3c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6883bfd-18a2-4828-9c01-a69a1e1f7c0b # USPs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5492e37-6b53-4405-a1dc-0df7c2af36c2
            userCondition: null
            warning: null
            width: 100
        name: 'USP Banner'
        uid: 44420ab4-d4c6-4d0d-97e7-f16269c66a62
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c28dc86-8f77-476c-8456-cb331ca86ef4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4299af30-f9c7-48d6-922c-045249174b4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bd420e7-c620-482a-a4f7-ee1433df6134
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b61af4-7baa-4d4d-8814-6dc66d180fe1 # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cec9dc0e-fee2-47ab-8b72-ee4c570590f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1bb40d-9000-497a-9b75-2f18c808ddd9 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8876a592-b1eb-4791-9d88-083d49b72a12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa573d0d-05be-480f-b5c8-2eb4c7420d0c # Lists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a026397-832f-4bcd-a740-04e6ce145d88
            userCondition: null
            warning: null
            width: 100
        name: 'Large Image Section'
        uid: 0372039d-66ed-4fb9-aaaf-539136b78d94
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3854bbb-1638-4a39-bd6a-ab2c0a42e483 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85348fcd-17bb-4474-ad87-14e2e0b7b015
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb2e6aac-abcc-4744-9ee7-250b2502df0d # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4976426f-6d1c-4e80-85cf-9cdcb321cd9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8be806db-3051-4e01-a8a8-823d359dbfd2 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a25c70cf-7c74-4a8d-baa1-c6adeb75b6f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31a6a6cd-809b-4018-b66d-eb3c366fc392 # TableEditor
            instructions: null
            label: 'Meeting Rooms Table'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92c31fa3-ef78-4fd4-bdb6-bd4e0456fe7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4673650a-aadd-4dc5-966e-7a5dba8f1d55 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab4b390c-4aec-4bb9-a216-9044f6e62024
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54fd7cdc-ab6d-487e-9f29-ebfd83f6715c # Intro Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbd310ea-0001-47ca-a9a8-2f1d771d968d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bb4d2ad-cdd2-47de-bd32-bdfe443c47bd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d9ed9ac-a44f-4688-9c25-d91cf9b748b3
            userCondition: null
            warning: null
            width: 100
        name: 'Table Section'
        uid: 6441d340-c8a3-4804-a119-ea371bc2b957
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8dedadfc-4af6-49f2-95bd-efef33a55b64 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ce68df0-ff5c-4ba7-abed-1b6fd752b8f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 750ece67-3956-41c0-9b8f-90dc48596ad9 # Heading
            instructions: null
            label: 'Intro Paragraph'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2be160b-b931-4017-95ff-f2dc0ef4ebff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 701d3032-1766-4e06-979c-fd973c6b51e8 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0a64214-2b09-4442-9f25-d6335ae25dd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 26dd4f0b-59ff-4617-974a-4ecc5a60c950 # Table Editor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96af164b-46ab-451a-b6c3-58ef8af1efe5
            userCondition: null
            warning: null
            width: 100
        name: 'Dark Section Table '
        uid: 5a365e1e-bd83-473e-96fe-e42d90395016
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0249f9a4-8d76-43b5-bf70-de0e1aebee56 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e28abf72-4d8a-4bfb-b8af-8d69f6c2d04a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2308c33-a2ac-480c-be85-0db8e054e2bd # Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21e94de7-5226-48aa-9874-dfb390201cc2
            userCondition: null
            warning: null
            width: 100
        name: 'Dark Section Grid'
        uid: 593d6a93-d4fa-4a4b-a244-c062b9f39f7e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34804f61-aab1-4122-8907-cc55a4677fa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98365502-6026-4d26-8636-d653c5ef86e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc5656c9-ee2c-497e-bab5-2bb3f236be53 # Footer Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddefd537-0b01-402b-acba-4edf3f9356f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89723374-3eac-4abc-b3ad-1bbd27091648 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edec9cb2-b164-4a38-b302-a1a65816d3e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea48c9dc-6e22-48a2-8f56-385fa9fa259e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6abc5ba5-50fb-4450-8edd-267b61d914d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b780b22-e03b-4537-bd01-74db803e4b3a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb074b40-f55a-4ce1-aaa3-01f93dd2225b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d08c9cda-b4c0-42b0-a7e5-c654a94f6fa2 # Pargraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbf81189-adb0-405c-bce6-80815e9f15e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d32e2df-7698-415c-9640-62e6787a0270 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9885cf14-efcd-4eca-b908-f2b2a19393fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d48d0ef1-ee78-4bd5-8dc8-21ad80e2eb5e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 607d8641-7cfa-44cc-8e8d-ecdb79d9422e
            userCondition: null
            warning: null
            width: 100
        name: 'Footer Section'
        uid: b499f474-b010-4520-a8d0-082938fc803e
        userCondition: null
handle: urbanmeet
hasTitleField: false
name: UrbanMeet
section: 08320fd1-0901-49fc-9707-c330852e1991 # UrbanMeet
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
