fieldLayouts:
  2b012d16-9d98-4c86-a6d3-e08bc0009e88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 938f8f0e-2e28-4c11-ba9d-8bab1051d4ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a64c6ea-1517-4f29-ba3b-d7ad5e5902d4
        userCondition: null
handle: urbanmeet
hasTitleField: false
name: UrbanMeet
section: 08320fd1-0901-49fc-9707-c330852e1991 # UrbanMeet
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
