columnSuffix: null
contentColumnType: string
fieldGroup: e39a23c1-ef67-42ee-b725-b0d5d9a96f76 # matrix
handle: buildingLink4
instructions: null
name: 'Building Link'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources:
    - singles
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
