columnSuffix: uqzneliq
contentColumnType: text
fieldGroup: 952787c6-7c0b-46f8-9b75-93ef54023e32 # Admin
handle: businessAddress
instructions: null
name: 'Business Address'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
