columnSuffix: fczcbvrl
contentColumnType: string(31)
fieldGroup: 952787c6-7c0b-46f8-9b75-93ef54023e32 # Admin
handle: contactDropdown
instructions: null
name: 'Contact Dropdown'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - '{{businessInformation.signIn}}'
        -
          - value
          - businessinformationSignin
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '{{businessInformation.footerBanner}}'
        -
          - value
          - businessinformationFooterbanner
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
