columnSuffix: null
contentColumnType: string
fieldGroup: e39a23c1-ef67-42ee-b725-b0d5d9a96f76 # matrix
handle: contactIntros
instructions: null
name: 'Contact Intros'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contactintros}}'
  maxBlocks: 3
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
