columnSuffix: azbuojgl
contentColumnType: text
fieldGroup: 4ce1e5c9-dab9-46f0-b32c-a5ac141e8eb3 # Events
handle: eventDescription
instructions: null
name: 'Event Description'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
