columnSuffix: null
contentColumnType: string
fieldGroup: e39a23c1-ef67-42ee-b725-b0d5d9a96f76 # matrix
handle: gridAddons
instructions: null
name: 'Grid Add-ons'
searchable: false
settings:
  contentTable: '{{%matrixcontent_gridaddons}}'
  maxBlocks: 2
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
