columnSuffix: ohxerjwj
contentColumnType: text
fieldGroup: bdaa862b-f4c9-44a8-8e83-355b31b152cb # Footer
handle: headingH3a
instructions: null
name: Heading
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: d5ebc5d3-29c4-49d3-970e-80907e54e5d9 # Title H3
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
