columnSuffix: skxksyqq
contentColumnType: text
fieldGroup: bdaa862b-f4c9-44a8-8e83-355b31b152cb # Footer
handle: heading8
instructions: null
name: Heading
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 33cfdfc6-431e-464c-917f-25271d27922c # Title H2
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
