columnSuffix: khkjxhen
contentColumnType: text
fieldGroup: d9af3e55-e89f-473c-a29a-abe18acebc79 # Common
handle: introParagraph4
instructions: null
name: 'Intro Paragraph'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
