columnSuffix: ezpcnlte
contentColumnType: text
fieldGroup: efebdbd4-c2aa-4fa3-af50-e6aaf0e04fdf # Heros
handle: pageName2
instructions: null
name: 'Page Name'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
