columnSuffix: pmzzynev
contentColumnType: text
fieldGroup: bdaa862b-f4c9-44a8-8e83-355b31b152cb # Footer
handle: paragraphF3
instructions: null
name: Paragraph
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 2d4fd05a-7931-4151-ac2a-8e3011088cd5 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
