columnSuffix: fenfnivz
contentColumnType: string(255)
fieldGroup: 952787c6-7c0b-46f8-9b75-93ef54023e32 # Admin
handle: signIn
instructions: null
name: 'Sign In'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
