columnSuffix: gnagqkiz
contentColumnType: text
fieldGroup: 952787c6-7c0b-46f8-9b75-93ef54023e32 # Admin
handle: tableeditor
instructions: null
name: TableEditor
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: c4688891-b1d6-4575-a601-60d55c055e0b # tables
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
