columnSuffix: nbaoruzw
contentColumnType: text
fieldGroup: d9af3e55-e89f-473c-a29a-abe18acebc79 # Common
handle: table
instructions: null
name: Table
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - ''
            -
              - handle
              - ''
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - ''
            -
              - handle
              - ''
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - ''
            -
              - handle
              - ''
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - ''
            -
              - handle
              - ''
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - ''
            -
              - handle
              - ''
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col6
        -
          __assoc__:
            -
              - heading
              - ''
            -
              - handle
              - ''
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
