columnSuffix: dzbmurud
contentColumnType: text
fieldGroup: d9af3e55-e89f-473c-a29a-abe18acebc79 # Common
handle: tableEditor2
instructions: null
name: 'Table Editor'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: c4688891-b1d6-4575-a601-60d55c055e0b # tables
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
