fieldLayouts:
  17c2f844-a2c1-4f90-a5e6-0c4129a72c40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24354e21-7f7c-4191-a61f-5d6193d33d90 # Sign In
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c8464bb-3089-46ee-9330-435765358ab0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c90d6d87-a43b-46cd-bca8-d634794723fc # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e97da23c-3103-4bee-860a-025aa0ae6350
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b75e7a02-75d5-4cc0-b393-073d25ca4714 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 424ef75f-a162-4589-9d9b-03cafeb1b502
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9375f2ff-8a06-4428-bbb6-de754ee5348c # Linkedin
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df830e06-babb-41ff-b6fa-17ff5e5c0c16
            userCondition: null
            warning: null
            width: 100
        name: Information
        uid: 8d5fdb9f-d972-4ad9-9b52-30f1bbdbe3be
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac6a4bbe-5e8b-41c7-997d-cb16dc2a14d2 # Business Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0ef5939-babf-43ff-8237-fa5dd6f77be2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0922d403-58e1-43e9-9968-a0d39895a2ef # Business Phone 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d3a98dd-8f1b-44d3-bd53-5a6f696bf42a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92ee1b66-7b2d-43c4-aefc-08ae23a54dda # Business Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0293498d-5a3d-4e57-a54b-125a1745d383
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7568988-4934-4d64-a04d-04c636118860 # Business Postal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0f227e2-6288-422b-babc-4c5548d06a79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0a1f864-9a0f-4bc8-931c-cb7d460030ba # Business Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d07201e-b3ea-4c47-91b0-af5c46b76ff7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82c50ae8-353d-4d5a-bbb3-08b969f2ee17 # Map Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dacba076-052a-4594-bb8f-11a948225f24
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Information'
        uid: 6398f4da-98e8-4a7c-aceb-6b64f6b0c8c2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94ae2f64-db35-47c0-907e-b853e95b3ce5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 756da4f7-2c1d-47d9-bca4-69b66630bd35
            userCondition: null
            warning: null
            width: 100
        name: 'Slider Title'
        uid: 7514e8cd-15a3-4356-a9e3-2f78682e53a6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 04877c62-92fa-436b-95c0-204552480b37 # Footer Banner
            instructions: null
            label: 'Footer Banner Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db86f31d-c189-4c02-bbc8-c2468f9e9802
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: 66ef66a3-2b28-49b0-84c0-bb75cb4d87ca
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2ee914a2-b05d-4c31-a59b-9919788305a7 # Image
            instructions: null
            label: 'Fallback Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 780fe921-de95-4370-b85d-91baf7d26ced
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 83c78d90-8c41-4ef1-a2ef-1c5110162342 # Image
            instructions: null
            label: 'Fallback Illustration'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f285e65e-7b29-4c0e-8f5e-433493c4e37d
            userCondition: null
            warning: null
            width: 100
        name: Misc
        uid: 02f830ba-3202-44bb-99d4-297ed87953ff
        userCondition: null
handle: businessInformation
name: 'Business Information'
sortOrder: 1
