defaultPlacement: end
enableVersioning: true
handle: cultureEvents
name: 'Culture & Events'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/culture-events.twig
    uriFormat: culture-events
type: single
