defaultPlacement: end
enableVersioning: true
handle: exploreOurSpaces
name: 'Explore Our Spaces'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/explore-our-spaces.twig
    uriFormat: explore-our-spaces
type: single
