defaultPlacement: end
enableVersioning: true
handle: facilitiesAmenities
name: 'Facilities & Amenities'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/facilities-amenities.twig
    uriFormat: facilities-amenities
type: single
