defaultPlacement: end
enableVersioning: true
handle: neighbourhood
name: Neighbourhood
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/neighbourhood.twig
    uriFormat: neighbourhood
type: single
