defaultPlacement: end
enableVersioning: true
handle: other
name: Other
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/other.twig
    uriFormat: other
type: single
