defaultPlacement: end
enableVersioning: true
handle: privacyPolicy
name: 'Privacy Policy'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/privacy-policy.twig
    uriFormat: privacy-policy
type: single
