defaultPlacement: end
enableVersioning: true
handle: storiesPage
name: 'Stories Page'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: stories/stories-page.twig
    uriFormat: stories
type: single
