defaultPlacement: end
enableVersioning: true
handle: termsConditions
name: 'Terms & Conditions'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: '_singles/ terms-conditions.twig'
    uriFormat: terms-conditions
type: single
