defaultPlacement: end
enableVersioning: true
handle: testPage
name: 'test page'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/test-page.twig
    uriFormat: test-page
type: single
