defaultPlacement: end
enableVersioning: true
handle: thankYou
name: 'Thank you'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/thank-you.twig
    uriFormat: thank-you
type: single
