defaultPlacement: end
enableVersioning: true
handle: urbanlease
name: UrbanLease
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/urban-lease.twig
    uriFormat: urban-lease
type: single
