defaultPlacement: end
enableVersioning: true
handle: urbanOffice
name: 'Urban Office'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/urban-office.twig
    uriFormat: urban-office
type: single
