defaultPlacement: end
enableVersioning: true
handle: urbanstudio
name: UrbanStudio
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/urban-studio.twig
    uriFormat: urban-studio
type: single
