defaultPlacement: end
enableVersioning: true
handle: urbanEnvironment
name: 'Urban Environment'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/urban-environment.twig
    uriFormat: urban-environment
type: single
