defaultPlacement: end
enableVersioning: true
handle: virtualTour
name: 'Virtual Tour'
propagationMethod: all
siteSettings:
  2995eac9-2c30-433a-bd61-0390ff903010: # urbanhub
    enabledByDefault: true
    hasUrls: true
    template: _singles/virtual-tour.twig
    uriFormat: virtual-tour
type: single
